version: '3.8'
services:
  app:
    image: c0ndi/twitter-clone-frontend:latest
    container_name: frontend
    build: .
    volumes:
      - ./pages:/app/src/pages
      - ./styles/:/app/src/styles
      - ./public/:/app/public
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=