version: '3.8'
services:
  web:
    image: c0ndi/twitter-clone-front:latest
    container_name: frontend
    build:
      context: ./
      target: runner
    volumes:
      - .:/pages
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=
