version: '3'
services:
  next-app:
    container_name: frontend
    image: c0ndi/twitter-clone-front:latest
    build:
      context: ./next-app
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=
    volumes:
      - ./next-app/src:/src
      - ./next-app/public:/public
    restart: always
    ports:
      - 3000:3000